server:
  port: 9091
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456

#使用jsp作为网页
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#      prefix: classpath:/templates/pages/
#      suffix: .html

#使用HTML作为网页
#  thymeleaf:
      ##    prefix: classpath:/templates/pages/  #prefix：指定模板所在的目录
      ##    #check-template-location: true  #check-tempate-location: 检查模板路径是否存在
      ##    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
      ##    suffix:  .html
      ##    #encoding: UTF-8
      ##    #content-type: text/html
    ##    #mode: HTML5
    ##    mode: LEGACYHTML5

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.cp.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

# pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.cp.mapper: debug